language: swift
osx_image: xcode12.1

cache:
  directories:
    - Carthage

before_install:
   - ./carthage.sh update --cache-builds --platform iOS

script:
  - xcodebuild test -project nugu-ios.xcodeproj -scheme NuguTests -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest'
