use_frameworks!
platform :ios, '10.0'

target 'SampleApp-iOS' do
  pod 'NuguLoginKit', :path => '../'
  pod 'NuguClientKit', :path => '../'
  pod 'NuguInterface', :path => '../'
  pod 'NuguCore', :path => '../'
  pod 'JadeMarble', :path => '../../jade-marble-ios'
  pod 'KeenSense', :path => '../../keen-sense-ios'

  pod 'NattyLog'
  pod 'lottie-ios'
end
