# root_url:
# dash_url:
# github_file_prefix:
# docset_playground_url:
# head:
module: NuguClientKit
output: ../docs/NuguClientKit
clean: true
sdk: iphone
author: SK Telecom Co., Ltd.
author_url: https://developers.nugu.co.kr
title: NUGU SDK iOS
copyright: (c) 2020 SK Telecom Co., Ltd. All rights reserved.
module_version: 0.27.5
readme: README.md
github_url: https://github.com/nugu-developers/nugu-ios
skip_undocumented: true
min_acl: public
hide_documentation_coverage: true
hide_unlisted_documentation: true
theme: apple
undocumented_text: Undocumented
custom_categories:
  - name: Common
    children:
    - logLevel
    - logEnabled
  - name: NuguClient
    children:
    - NuguClient
    - NuguClientDelegate
  - name: VoiceChromePresenter
    children:
    - VoiceChromePresenter
    - VoiceChromePresenterDelegate
    - VoiceChromePresenterError
  - name: DialogStateAggregator
    children:
    - DialogStateAggregator
    - DialogStateDelegate
    - DialogState
  - name: MicInputProvider
    children:
    - MicInputProvider
    - MicInputError
  - name: KeywordDetector
    children:
    - KeywordDetector
    - KeywordDetectorDelegate
    - KeywordDetectorState
    - KeywordSource