podspec: NuguCore.podspec
output: ../docs/NuguCore
skip_undocumented: true

custom_categories:
  - name: Common
    children:
    - logLevel
    - NuguServerInfo
  - name: Authorization
    children:
    - AuthorizationStoreable
    - AuthorizationStoreDelegate
  - name: Michrophone
    children:
    - MicInputProvider
    - MicInputError
  - name: Network
    children:
    - StreamDataRoutable
    - StreamDataDelegate
    - StreamDataState
    - EventSenderError
    - NetworkError
    - UpstreamDataSendable
    - Upstream
    - Downstream
    - TimeUUID
  - name: AudioFocus
    children:
    - FocusManageable
    - FocusDelegate
    - FocusChannelDelegate
    - FocusChannelPriority
    - FocusState
  - name: DirectiveSequener
    children:
    - DirectiveSequenceable
    - DirectiveSequencerDelegate
    - BlockingPolicy
    - DirectiveHandleInfo
    - Array
    - DirectiveHandleInfos
    - PrefetchDirective
    - HandleDirective
    - CancelDirective
    - HandleAttachment
    - DirectiveHandleResult
    - DirectiveCancelPolicy
  - name: Context
    children:
    - ContextManageable
    - ContextInfoDelegate
    - ContextInfo
    - ContextType
  - name: LayerPolicy
    children:
    - PlaySyncManageable
    - PlaySyncDelegate
    - PlaySyncProperty
    - PlaySyncInfo
  - name: MediaPlayer
    children:
    - MediaPlayable
    - MediaPlayerDelegate
    - MediaPlayerState
    - MediaPlayableError
  - name: TimeIntervallic
    children:
    - TimeIntervallic
    - NuguTimeInterval
    - CMTime
    - DispatchTimeInterval
  
